export const ITEM_REQUEST_INITIATED = "FETECT_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETECT_ITEMS_SUCCESS";
export const FETCH_ITEMS_ERROR = "FETECT_ITEMS_ERROR";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";

export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";

export const FETCH_CARTITEM_REQUEST = "FETCH_CARTITEM_REQUEST";
export const FETCH_CARTITEM_SUCCESS = "FETCH_CARTITEM_SUCCESS";
export const FETCH_CARTITEM_ERROR = "FETCH_CARTITEM_ERROR";
export const MERGE_CARTITEMS = "MERGE_CARTITEMS";
// export const CREATE_CARTITEM_

export const FETCH_AUTHORISATION_REQUEST = "FETCH_AUTHORISATION_REQUEST";
export const FETCH_AUTHORISATION_SUCCESS = "FETCH_AUTHORISATION_SUCCESS";
export const FETCH_AUTHORISATION_ERROR = "FETCH_AUTHORISATION_ERROR";

export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR";

export const FETCH_ADDRESS_REQUEST = "FETCH_ADDRESS_REQUEST";
export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESS_ERROR = "FETCH_ADDRESS_ERROR";