export const ITEM_REQUEST_INITIATED = "ITEM_REQUEST_INITIATED";
export const ITEM_REQUEST_SUCCESS = "ITEM_REQUEST_SUCCESS";
export const ITEM_REQUEST_FAILED = "ITEM_REQUEST_FAILED";

export const CATEGORY_REQUEST_INITIATED = "CATEGORY_REQUEST_INITIATED";
export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const CATEGORY_REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";

export const CART_REQUEST_INITIATED = "CART_REQUEST_INITIATED";
export const CART_REQUEST_SUCCESS = "CART_REQUEST_SUCCESS";
export const CART_REQUEST_FAILED = "CART_REQUEST_FAILED";

export const CARTITEM_REQUEST_INITIATED = "CARTITEM_REQUEST_INITIATED";
export const CARTITEM_REQUEST_SUCCESS = "CARTITEM_REQUEST_SUCCESS";
export const CARTITEM_REQUEST_FAILED = "CARTITEM_REQUEST_FAILED";
export const MERGE_CARTITEMS = "MERGE_CARTITEMS";
// export const CREATE_CARTITEM_

export const FETCH_AUTHORISATION_REQUEST = "FETCH_AUTHORISATION_REQUEST";
export const FETCH_AUTHORISATION_SUCCESS = "FETCH_AUTHORISATION_SUCCESS";
export const FETCH_AUTHORISATION_ERROR = "FETCH_AUTHORISATION_ERROR";

export const ORDER_REQUEST_INITIATED = "ORDER_REQUEST_INITIATED";
export const ORDER_REQUEST_SUCCESS = "ORDER_REQUEST_SUCCESS";
export const ORDER_REQUEST_FAILED = "ORDER_REQUEST_FAILED";

export const ADDRESS_REQUEST_INITIATED = "ADDRESS_REQUEST_INITIATED";
export const ADDRESS_REQUEST_SUCCESS = "ADDRESS_REQUEST_SUCCESS";
export const ADDRESS_REQUEST_FAILED = "ADDRESS_REQUEST_FAILED";

export const PACKAGE_REQUEST_INITIATED = "PACKAGE_REQUEST_INITIATED";
export const PACKAGE_REQUEST_SUCCESS = "PACKAGE_REQUEST_SUCCESS";
export const PACKAGE_REQUEST_FAILED = "PACKAGE_REQUEST_FAILED";