export const FETCH_ITEMS_REQUEST = "FETECT_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETECT_ITEMS_SUCCESS";
export const FETCH_ITEMS_ERROR = "FETECT_ITEMS_ERROR";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";